version: '3.8'

services:
  mcp-content-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: mcp-content-analyzer
    restart: unless-stopped

    # Environment variables
    environment:
      - NODE_ENV=production
      - EXCEL_DATABASE_PATH=/app/data/content-database.xlsx
      - EXCEL_BACKUP_ENABLED=true
      - MCP_SERVER_PORT=3000
      - TEAM_NAME=${TEAM_NAME:-default}
      - LOG_LEVEL=info

    # Volumes for persistent data
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./config:/app/config:ro

    # Port mapping (if using Hono web server)
    ports:
      - "3000:3000"

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Redis for caching (team deployments)
  redis:
    image: redis:7-alpine
    container_name: mcp-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: mcp-network